### PR TITLE
[1.x] Prevent `pulse:check` from filling the file cache

### LINKED ISSUE #238: Server storage is filled with cache data
### Pulse Version

1.0.0

### Laravel Version

10.4

### PHP Version

8.2

### Livewire Version

3.0.2

### Database Driver & Version

mysql 8

### Description

Pulse if filling the server with a lot of files and cached data for no obvious reason , this is causing the server to run out of space 
image

image

### Steps To Reproduce

visit laravel pulse url (localhost:8000/pulse) and monitor the  storage/framework/cache/data directory , you will find that the content of this file is duplicated each refresh

### PR DESCRIPTION
**Pull request by jessarcher**
This PR fixes an issue when using the file cache driver where the cache locks would continue growing on disk. This is due to the file cache driver not automatically removing files when the cache item has expired.

Fixes #238

### CODE REVIEW

**Comment by jessarcher** [comment]
Building failing until #261 is merged.

File: src/Commands/CheckCommand.php [hunk 1]
```diff
@@ -63,15 +67,12 @@ public function handle(
 
             $lastSnapshotAt = $now->floorSeconds((int) $interval->totalSeconds);
 
-            $event->dispatch(new SharedBeat($lastSnapshotAt, $interval));
-
-            if (
-                ($lockProvider ??= $cache->store()->getStore()) instanceof LockProvider &&
-                $lockProvider->lock("laravel:pulse:check:{$lastSnapshotAt->getTimestamp()}", (int) $interval->totalSeconds)->get()
-            ) {
+            if ($lock && $lock->get()) {
```
Comment (timacdonald) [inline src/Commands/CheckCommand.php:70]:
```suggestion
            if ($lock?->get()) {
```

**Review by timacdonald — APPROVED** [review]

File: src/Commands/CheckCommand.php (hunk 1 above)
Comment (jessarcher) [reply src/Commands/CheckCommand.php]: :clinking_glasses:
