### PR TITLE
[1.x] Fix DB prefixing for Postgres and SQLite

### LINKED ISSUE #385: Add table prefix on raw expressions when a table name is in the string
### Pulse Version

v1.2.1

### Laravel Version

11.8.0

### PHP Version

8.2.12

### Livewire Version

3.5.0

### Database Driver & Version

Postgres 13

### Description

I don't know if this can be considered a bug ...

When using a raw Expression consider using the table-prefix before the table name if the table name is hardcoded
I have table names prefixed with 'kp_' and pulse throws the following exception:

```
#18 {main}An exception happened in PulseSQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "pulse_aggregates"
LINE 1: ... "aggregate", "key_hash") do update set "value" = "pulse_agg...
                                                             ^ (Connection: pgsql, SQL: insert into "kp_pulse_aggregates" ("aggregate", "bucket", "key", "period", "type", "value") values (count, 1717076700, ["select count(*) as aggregate from \"kp_migrations\"","C:\\Software\\kp\\api\\vendor\\laravel\\pulse\\src\\Pulse.php:594"], 60, slow_query, 1), (count, 1717076520, ["select count(*) as aggregate from \"kp_migrations\"","C:\\Software\\kp\\api\\vendor\\laravel\\pulse\\src\\Pulse.php:594"], 360, slow_query, 1), (count, 1717076160, ["select count(*) as aggregate from \"kp_migrations\"","C:\\Software\\kp\\api\\vendor\\laravel\\pulse\\src\\Pulse.php:594"], 1440, slow_query, 1), (count, 1717067520, ["select count(*) as aggregate from \"kp_migrations\"","C:\\Software\\kp\\api\\vendor\\laravel\\pulse\\src\\Pulse.php:594"], 10080, slow_query, 1) on conflict ("bucket", "period", "type", "aggregate", "key_hash") do update set "value" = "pulse_aggregates"."value" + "excluded"."value")
```

avoid this behavior by using `$this->connection()->getTablePrefix()`  just before the table name  in `src/Storage/DatabaseStorage.php`

Eg.
```php
            match ($driver = $this->connection()->getDriverName()) {
                'mariadb', 'mysql' => [
                    'value' => new Expression('(`value` * `count` + (values(`value`) * values(`count`))) / (`count` + values(`count`))'),
                    'count' => new Expression('`count` + values(`count`)'),
                ],
                'pgsql', 'sqlite' => [
                    'value' => new Expression('("' . $this->connection()->getTablePrefix() . 'pulse_aggregates"."value" * "' . $this->connection()->getTablePrefix() . 'pulse_aggregates"."count" + ("excluded"."value" * "excluded"."count")) / ("' . $this->connection()->getTablePrefix() . 'pulse_aggregates"."count" + "excluded"."count")'),
                    'count' => new Expression('"' . $this->connection()->getTablePrefix() . 'pulse_aggregates"."count" + "excluded"."count"'),
                ],
                default => throw new RuntimeException("Unsupported database driver [{$driver}]"),
            }

```
Regards
S.

### Steps To Reproduce

Put in .env

`DB_PREFIX=kp_`

### PR DESCRIPTION
**Pull request by jessarcher**
This PR fixes an issue for Postgres and SQLite users with database prefixes enabled where some queries did include the prefix.

I've tested this locally but have not included additional CI jobs due to the extra overhead required to test each database with and without prefixes.

Fixes #385

### CODE REVIEW

File: src/Storage/DatabaseStorage.php [hunk 1]
```diff
@@ -179,7 +179,9 @@ protected function upsertCount(array $values): int
             [
                 'value' => match ($driver = $this->connection()->getDriverName()) {
                     'mariadb', 'mysql' => new Expression('`value` + values(`value`)'),
-                    'pgsql', 'sqlite' => new Expression('"pulse_aggregates"."value" + "excluded"."value"'),
+                    'pgsql', 'sqlite' => new Expression(<<<SQL
+                        {$this->wrap('pulse_aggregates.value')} + "excluded"."value"
```
Comment (jessarcher) [inline src/Storage/DatabaseStorage.php:183]: I opted to leave the `"excluded"."value"` "raw" because `excluded` is a special keyword in this scenario and should not be prefixed.

**Review by timacdonald — APPROVED** [review]
